[workspace.package]
version = "0.1.0"
description = "Iced Snippets"

[workspace]
resolver = "2"
members = ["snippets/*"]


[workspace.dependencies]
iced = { version = "0.13.1", features = ["advanced", "image", "tokio", "debug", "lazy"]}
tokio = { version = "1", features = ["full"] }