[package]
edition = "2021"
name = "subscription"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {version = "0.10.0", features = ["tokio", "advanced", "lazy"]}
